import { INITIAL_EMPLOYEES, INITIAL_SETTINGS, INITIAL_HISTORY } from '../data/initialData.js';
import { toISODateString, getWorkDaysOfWeek } from '../utils/timeUtils.js';

const STORAGE_KEYS = {
  EMPLOYEES: 'scadahub_rodizio_employees_v2',
  SCHEDULES: 'scadahub_rodizio_schedules_v2',
  SETTINGS: 'scadahub_rodizio_settings_v2',
  HISTORY: 'scadahub_rodizio_history_v2'
};

/**
 * Cria a escala padrão inicial para a semana corrente,
 * garantindo cobertura contínua de atendimento entre 11:30 e 13:30.
 */
function createInitialWeekSchedules(employees) {
  const today = new Date();
  const workdays = getWorkDaysOfWeek(today);
  const schedules = {};

  // Duplas de revezamento para garantir sempre pessoas trabalhando
  // Turno 1: 11:45 - 12:15
  // Turno 2: 12:35 - 13:05
  workdays.forEach((day, dayIndex) => {
    const daySlots = [];

    employees.forEach((emp, empIndex) => {
      // Revezamento alternado por dia para rotacionar turnos
      const isTurn1 = (empIndex + dayIndex) % 2 === 0;
      const startTime = isTurn1 ? '11:45' : '12:35';
      const endTime = isTurn1 ? '12:15' : '13:05';

      daySlots.push({
        id: `slot-${day.date}-${emp.id}`,
        employeeId: emp.id,
        date: day.date,
        startTime,
        endTime,
        duration: 30,
        isAutoGenerated: true
      });
    });

    schedules[day.date] = daySlots;
  });

  return schedules;
}

export const storageService = {
  getEmployees: () => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.EMPLOYEES);
      return data ? JSON.parse(data) : INITIAL_EMPLOYEES;
    } catch (e) {
      return INITIAL_EMPLOYEES;
    }
  },

  saveEmployees: (employees) => {
    try {
      localStorage.setItem(STORAGE_KEYS.EMPLOYEES, JSON.stringify(employees));
    } catch (e) {
      console.error('Erro ao salvar funcionários:', e);
    }
  },

  getSettings: () => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.SETTINGS);
      return data ? { ...INITIAL_SETTINGS, ...JSON.parse(data) } : INITIAL_SETTINGS;
    } catch (e) {
      return INITIAL_SETTINGS;
    }
  },

  saveSettings: (settings) => {
    try {
      localStorage.setItem(STORAGE_KEYS.SETTINGS, JSON.stringify(settings));
    } catch (e) {
      console.error('Erro ao salvar configurações:', e);
    }
  },

  getAllSchedules: () => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.SCHEDULES);
      if (data) {
        return JSON.parse(data);
      }
      const employees = storageService.getEmployees();
      const initialSchedules = createInitialWeekSchedules(employees);
      storageService.saveAllSchedules(initialSchedules);
      return initialSchedules;
    } catch (e) {
      return {};
    }
  },

  saveAllSchedules: (schedules) => {
    try {
      localStorage.setItem(STORAGE_KEYS.SCHEDULES, JSON.stringify(schedules));
    } catch (e) {
      console.error('Erro ao salvar escalas:', e);
    }
  },

  getDaySchedule: (dateString) => {
    const all = storageService.getAllSchedules();
    return all[dateString] || [];
  },

  saveDaySchedule: (dateString, slots) => {
    const all = storageService.getAllSchedules();
    all[dateString] = slots;
    storageService.saveAllSchedules(all);
    return slots;
  },

  getHistory: () => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.HISTORY);
      if (data) {
        const parsed = JSON.parse(data);
        // Se for o mock antigo (ex: contagens acumuladas artificiais de 13/14 turnos), limpa automaticamente
        const hasLegacyMock = parsed && typeof parsed === 'object' && Object.values(parsed).some(
          (v) => v && typeof v === 'object' && ((v['11h-12h'] || 0) + (v['12h-13h'] || 0) + (v['13h-14h'] || 0) >= 10)
        );
        if (hasLegacyMock) {
          localStorage.removeItem(STORAGE_KEYS.HISTORY);
          return {};
        }
        return parsed || {};
      }
      return {};
    } catch (e) {
      return {};
    }
  },

  saveHistory: (history) => {
    try {
      localStorage.setItem(STORAGE_KEYS.HISTORY, JSON.stringify(history));
    } catch (e) {
      console.error('Erro ao salvar histórico:', e);
    }
  },

  resetAllData: () => {
    localStorage.removeItem(STORAGE_KEYS.EMPLOYEES);
    localStorage.removeItem(STORAGE_KEYS.SCHEDULES);
    localStorage.removeItem(STORAGE_KEYS.SETTINGS);
    localStorage.removeItem(STORAGE_KEYS.HISTORY);
    window.location.reload();
  },

  exportAsJSON: () => {
    const payload = {
      brand: 'scadahub',
      version: '2.0',
      exportedAt: new Date().toISOString(),
      employees: storageService.getEmployees(),
      settings: storageService.getSettings(),
      schedules: storageService.getAllSchedules(),
      history: storageService.getHistory()
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scadahub_rodizio_backup_${toISODateString(new Date())}.json`;
    a.click();
    URL.revokeObjectURL(url);
  },

  exportDayToCSV: (dateString, employees, slots) => {
    const empMap = Object.fromEntries(employees.map((e) => [e.id, e.name]));
    let csv = 'Data;Funcionario;Inicio;Fim;Duracao(min)\n';
    slots.forEach((slot) => {
      const name = empMap[slot.employeeId] || slot.employeeId;
      csv += `${dateString};${name};${slot.startTime};${slot.endTime};${slot.duration || 30}\n`;
    });
    const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scadahub_escala_${dateString}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  },

  importFromJSON: (jsonString) => {
    try {
      const data = JSON.parse(jsonString);
      if (data.employees) storageService.saveEmployees(data.employees);
      if (data.settings) storageService.saveSettings(data.settings);
      if (data.schedules) storageService.saveAllSchedules(data.schedules);
      if (data.history) storageService.saveHistory(data.history);
      return { success: true, message: 'Dados restaurados com sucesso!' };
    } catch (e) {
      return { success: false, message: 'Arquivo JSON inválido.' };
    }
  }
};
