import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getDatabase, ref, get } from 'firebase/database';
import { firebaseService } from '../src/services/firebaseService.js';
import { defaultFirebaseConfig } from '../src/firebaseConfig.js';

// Testes REAIS contra o Realtime Database de produção, sempre numa data de teste isolada (2099-12-31),
// que é limpa ao final. Nenhum dado real da equipe é alterado.
const TEST_DATE = '2099-12-31';
const DB_URL = defaultFirebaseConfig.databaseURL.replace(/\/+$/, '');

const USERS = [
  { id: 'emp-1', name: 'Mateus Silva', start: '12:30', end: '13:30', duration: 60 },
  { id: 'emp-2', name: 'Mateus Gomes (admin)', start: '12:00', end: '12:30', duration: 30 },
  { id: 'emp-3', name: 'Monique', start: '11:45', end: '12:15', duration: 30 },
  { id: 'emp-4', name: 'Samara', start: '12:30', end: '13:10', duration: 40 }
];

const makeSlot = (u) => ({
  id: `slot-${TEST_DATE}-${u.id}`,
  employeeId: u.id,
  date: TEST_DATE,
  startTime: u.start,
  endTime: u.end,
  duration: u.duration,
  isAutoGenerated: false
});

async function restGet(path) {
  const res = await fetch(`${DB_URL}/${path}.json`);
  assert.equal(res.ok, true, `GET ${path} deve responder 200`);
  return res.json();
}

async function restDelete(path) {
  await fetch(`${DB_URL}/${path}.json`, { method: 'DELETE' });
}

// Leitor independente (cliente "outra máquina") usando o SDK oficial em um app separado
function getIndependentReader() {
  const name = 'independent-reader';
  const existing = getApps().find((a) => a.name === name);
  const app = existing || initializeApp(defaultFirebaseConfig, name);
  return getDatabase(app);
}

async function waitFor(condition, timeoutMs, label) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (await condition()) return;
    await new Promise((r) => setTimeout(r, 200));
  }
  assert.fail(`Tempo esgotado aguardando: ${label}`);
}

after(async () => {
  await restDelete(`scadahub_schedules/${TEST_DATE}`);
  setTimeout(() => process.exit(0), 100).unref();
});

test('SYNC 1: Cada um dos 4 usuários grava o próprio almoço (modo SDK/WebSocket) e TODOS enxergam os 4', async () => {
  await restDelete(`scadahub_schedules/${TEST_DATE}`);
  firebaseService.init();

  const received = [];
  let connected = false;
  const unsubscribe = firebaseService.subscribe({
    onSchedules: (all) => received.push(all),
    onEmployees: () => {},
    onSettings: () => {},
    onConnectionStatus: (isOnline) => { if (isOnline) connected = true; }
  });

  try {
    await waitFor(() => connected, 20000, 'conexão WebSocket do Firebase');
    assert.equal(firebaseService.isConnected, true);

    for (const u of USERS) {
      const ok = await firebaseService.pushSlot(TEST_DATE, makeSlot(u));
      assert.equal(ok, true, `${u.name} deve conseguir gravar o próprio almoço`);
    }

    // Leitor independente (como se fosse a máquina de cada colega)
    const reader = getIndependentReader();
    const snap = await get(ref(reader, `scadahub_schedules/${TEST_DATE}`));
    const remote = Object.values(snap.val() || {});
    for (const viewer of USERS) {
      for (const owner of USERS) {
        const found = remote.find((s) => s.employeeId === owner.id);
        assert.ok(found, `${viewer.name} deve enxergar o almoço de ${owner.name}`);
        assert.equal(found.startTime, owner.start);
      }
    }

    // O próprio ouvinte em tempo real recebeu a escala completa do dia
    await waitFor(
      () => received.some((all) => (all[TEST_DATE] || []).length === 4),
      10000,
      'evento em tempo real com os 4 horários'
    );
  } finally {
    unsubscribe();
  }
});

test('SYNC 2: Redes que bloqueiam o WebSocket - leitura e escrita continuam funcionando via HTTPS', async () => {
  await restDelete(`scadahub_schedules/${TEST_DATE}`);

  // Cliente cujo SDK NUNCA conecta (simula proxy bloqueando WebSocket) mas com HTTPS liberado
  const blockedClient = new firebaseService.constructor();
  const deadApp = initializeApp({ ...defaultFirebaseConfig, databaseURL: 'http://127.0.0.1:9/?ns=bloqueado' }, 'ws-bloqueado');
  blockedClient.app = deadApp;
  blockedClient.db = getDatabase(deadApp);
  blockedClient.isInitialized = true;
  blockedClient.getRestBaseUrl = () => DB_URL;
  assert.equal(blockedClient.isConnected, false);

  // Escrita: Samara lança o almoço e ele PRECISA chegar na nuvem mesmo sem WebSocket
  const samara = USERS[3];
  assert.equal(await blockedClient.pushSlot(TEST_DATE, makeSlot(samara)), true, 'Gravação via HTTPS deve concluir');
  const stored = await restGet(`scadahub_schedules/${TEST_DATE}/slot-${TEST_DATE}-emp-4`);
  assert.equal(stored.employeeId, 'emp-4');
  assert.equal(stored.startTime, '12:30');

  // Colegas gravam normalmente (cliente saudável)
  for (const u of USERS.slice(0, 3)) {
    assert.equal(await firebaseService.pushSlot(TEST_DATE, makeSlot(u)), true);
  }

  // Leitura: a máquina bloqueada passa a receber os horários de todos via polling HTTPS
  const received = [];
  const statuses = [];
  const unsubscribe = blockedClient.subscribe({
    onSchedules: (all) => received.push(all),
    onEmployees: () => {},
    onSettings: () => {},
    onConnectionStatus: (isOnline, status) => statuses.push({ isOnline, status })
  });

  try {
    await waitFor(
      () => received.some((all) => (all[TEST_DATE] || []).length === 4),
      15000,
      'recebimento dos 4 horários via contingência HTTPS'
    );
    const day = received.find((all) => (all[TEST_DATE] || []).length === 4)[TEST_DATE];
    for (const u of USERS) {
      assert.ok(day.find((s) => s.employeeId === u.id), `Máquina bloqueada deve enxergar ${u.name}`);
    }
    assert.ok(statuses.some((s) => s.status === 'rest_fallback' && s.isOnline === true));

    // Remoção também funciona sem WebSocket
    assert.equal(await blockedClient.deleteSlot(TEST_DATE, `slot-${TEST_DATE}-emp-4`), true);
    assert.equal(await restGet(`scadahub_schedules/${TEST_DATE}/slot-${TEST_DATE}-emp-4`), null);
  } finally {
    unsubscribe();
  }
});

test('SYNC 3: Edição do admin (estado local defasado) NÃO apaga o almoço dos demais', async () => {
  await restDelete(`scadahub_schedules/${TEST_DATE}`);

  // Nuvem já contém Monique e Samara
  await firebaseService.pushSlot(TEST_DATE, makeSlot(USERS[2]));
  await firebaseService.pushSlot(TEST_DATE, makeSlot(USERS[3]));

  // Admin com estado local defasado (só conhece emp-1 e emp-2) ajusta o horário do Mateus Silva.
  // O App agora grava somente o slot alterado.
  const staleAdminEdit = { ...makeSlot(USERS[0]), startTime: '12:20', endTime: '13:00', duration: 40 };
  assert.equal(await firebaseService.pushSlot(TEST_DATE, staleAdminEdit), true);

  const day = Object.values(await restGet(`scadahub_schedules/${TEST_DATE}`));
  assert.equal(day.length, 3, 'Os horários de Monique e Samara devem ser preservados');
  assert.ok(day.find((s) => s.employeeId === 'emp-3'));
  assert.ok(day.find((s) => s.employeeId === 'emp-4'));
  assert.equal(day.find((s) => s.employeeId === 'emp-1').startTime, '12:20');

  // Exclusão pontual também preserva os demais
  assert.equal(await firebaseService.deleteSlot(TEST_DATE, `slot-${TEST_DATE}-emp-1`), true);
  const afterDelete = Object.values(await restGet(`scadahub_schedules/${TEST_DATE}`));
  assert.equal(afterDelete.length, 2);
});

test('SYNC 4: Leituras de perfil/equipe (login) funcionam sem WebSocket e retornam os 4 colaboradores', async () => {
  const cold = new firebaseService.constructor();
  cold.init();
  cold.getRestBaseUrl = () => DB_URL;
  assert.equal(cold.isConnected, false);

  const employees = await cold.getEmployees();
  assert.ok(Array.isArray(employees));
  const ids = employees.map((e) => e.id).sort();
  assert.deepEqual(ids, ['emp-1', 'emp-2', 'emp-3', 'emp-4']);
  assert.ok(employees.every((e) => e.active === true), 'Todos os colaboradores devem estar ativos na escala');

  const adminUid = Object.keys(await restGet('scadahub_admins'))[0];
  assert.equal(await cold.checkIfAdmin(adminUid), true);
  assert.equal(await cold.checkIfAdmin('uid-inexistente'), false);
  const record = await cold.getUserRecord(adminUid);
  assert.equal(record.employeeId, 'emp-2');
});

test('SYNC 5: App não sobrescreve a nuvem inteira a partir do estado local nas edições individuais', () => {
  const app = fs.readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8');

  const slotHandlers = app.slice(app.indexOf('const handleSaveSlot'), app.indexOf('// Aplicação de escala gerada'));
  assert.ok(slotHandlers.length > 200);
  assert.ok(!slotHandlers.includes('pushDaySchedule'), 'Salvar/excluir/arrastar slot não pode enviar o dia inteiro');
  assert.ok(!slotHandlers.includes('pushAllSchedules'));

  const teamHandlers = app.slice(app.indexOf('const handleSaveEmployee'), app.indexOf('// Salvar Configurações'));
  assert.ok(teamHandlers.length > 200);
  assert.ok(!teamHandlers.includes('pushEmployees('), 'Cadastro/exclusão não pode regravar a lista inteira da equipe');
  assert.ok(!teamHandlers.includes('pushAllSchedules'));

  const weekHandler = app.slice(app.indexOf('const handleApplyWeekSchedule'), app.indexOf('const handleSaveEmployee'));
  assert.ok(!weekHandler.includes('pushAllSchedules'), 'Escala semanal envia somente os dias gerados');
});

test('SYNC 6: CSP permite o long-polling do Firebase (script-src com *.firebaseio.com)', () => {
  const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
  const csp = html.match(/Content-Security-Policy"\s+content="([^"]+)"/)[1];
  const scriptSrc = csp.split(';').map((d) => d.trim()).find((d) => d.startsWith('script-src'));
  assert.ok(scriptSrc.includes('https://*.firebaseio.com'));
  assert.ok(csp.includes('wss://*.firebaseio.com'));
  assert.ok(getApp()); // app padrão inicializado
});
