import React, { useState, useEffect } from 'react';
import { X, Clock, AlertTriangle, Check, Trash2, Wand2, Calendar } from 'lucide-react';
import { timeToMinutes, minutesToTime, addMinutesToTime, snapToInterval } from '../utils/timeUtils';
import { findNextAvailableSlot } from '../utils/scheduler';

export default function EditSlotModal({
  isOpen,
  onClose,
  slot,
  employee,
  employees,
  daySlots,
  settings,
  date,
  onSave,
  onDelete
}) {
  if (!isOpen) return null;

  const [startTime, setStartTime] = useState(slot ? slot.startTime : '12:00');
  const [duration, setDuration] = useState(slot ? slot.duration || 30 : settings.defaultDuration || 30);
  const [endTime, setEndTime] = useState(
    slot ? slot.endTime : addMinutesToTime('12:00', settings.defaultDuration || 30)
  );
  const [conflictWarning, setConflictWarning] = useState(null);
  const [sharedShiftNames, setSharedShiftNames] = useState([]);

  // Recalcula o horário de término quando o início ou duração mudam
  useEffect(() => {
    const end = addMinutesToTime(startTime, duration);
    setEndTime(end);
  }, [startTime, duration]);

  // Checa se a alteração deste horário compromete o atendimento aos clientes (11:30 - 13:30)
  useEffect(() => {
    const startMin = timeToMinutes(startTime);
    const endMin = timeToMinutes(endTime);
    const otherSlots = daySlots.filter((s) => s.id !== slot?.id);

    // Identifica colegas almoçando no mesmo intervalo
    const sameShift = [];
    otherSlots.forEach((other) => {
      const oStart = timeToMinutes(other.startTime);
      const oEnd = timeToMinutes(other.endTime);
      if (Math.max(startMin, oStart) < Math.min(endMin, oEnd)) {
        const otherEmp = employees.find((e) => e.id === other.employeeId);
        sameShift.push(otherEmp?.name || 'Colega');
      }
    });
    setSharedShiftNames(sameShift);

    // Valida se na janela crítica (11:30 às 13:30) há pelo menos 1 pessoa trabalhando a cada minuto
    const critStartMin = timeToMinutes(settings.criticalStart || '11:30');
    const critEndMin = timeToMinutes(settings.criticalEnd || '13:30');
    const minWorking = settings.minWorkingDuringCritical || 1;
    const activeEmps = employees.filter((e) => e.active);

    const simulatedSlots = [
      ...otherSlots,
      { id: slot?.id || 'temp', employeeId: employee?.id, startTime, endTime, duration }
    ];

    let uncoveredMinutes = 0;
    for (let m = critStartMin; m < critEndMin; m += 5) {
      let workingCount = 0;
      activeEmps.forEach((emp) => {
        const empSlot = simulatedSlots.find((s) => s.employeeId === emp.id);
        if (empSlot) {
          const sMin = timeToMinutes(empSlot.startTime);
          const eMin = timeToMinutes(empSlot.endTime);
          if (m < sMin || m >= eMin) workingCount++;
        } else {
          workingCount++;
        }
      });
      if (workingCount < minWorking) {
        uncoveredMinutes += 5;
      }
    }

    if (uncoveredMinutes > 0) {
      setConflictWarning(
        `Atenção: Este horário deixará o atendimento ao cliente desassistido por ${uncoveredMinutes} min entre 11:30h e 13:30h!`
      );
    } else {
      setConflictWarning(null);
    }
  }, [startTime, endTime, duration, daySlots, slot, employee, employees, settings]);

  const handleAdjustStart = (deltaMinutes) => {
    const currentMin = timeToMinutes(startTime);
    const startLimit = timeToMinutes(settings.startHour || '11:00');
    const endLimit = timeToMinutes(settings.endHour || '14:00');
    const interval = Number(settings?.slotInterval) || 5;

    const newMin = Math.max(startLimit, Math.min(endLimit - duration, currentMin + deltaMinutes));
    setStartTime(minutesToTime(snapToInterval(newMin, interval)));
  };

  const handleSuggestSlot = () => {
    const suggestion = findNextAvailableSlot(daySlots, duration, settings, slot?.id);
    if (suggestion) {
      setStartTime(suggestion.startTime);
      setEndTime(suggestion.endTime);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    onSave({
      id: slot ? slot.id : `slot-${date}-${employee.id}`,
      employeeId: employee.id,
      date,
      startTime,
      endTime,
      duration,
      isAutoGenerated: false
    });
    onClose();
  };

  const currentInterval = Number(settings?.slotInterval) || 5;

  return (
    <div className="modal-backdrop animate-fade-in" onClick={onClose}>
      <div className="modal-card animate-scale-up" onClick={(e) => e.stopPropagation()}>
        {/* Cabeçalho do Modal */}
        <div className="modal-header">
          <div className="modal-title-wrap">
            <Clock size={19} className="text-scada-cyan" />
            <div>
              <h3 className="modal-title">{slot ? 'Editar Almoço' : 'Definir Almoço'}</h3>
              <span className="modal-subtitle">Ajuste o horário com precisão configurada ({currentInterval} min)</span>
            </div>
          </div>
          <button type="button" className="btn-modal-close" onClick={onClose}>
            <X size={18} />
          </button>
        </div>

        {/* Corpo do Modal */}
        <form onSubmit={handleSubmit} className="modal-form">
          {/* Card do Funcionário */}
          <div className="modal-emp-badge" style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 16px', background: 'var(--bg-subtle)', borderRadius: 'var(--radius-lg)', marginBottom: '16px' }}>
            <div
              className="emp-avatar-modal"
              style={{
                backgroundColor: employee?.color || '#381267',
                width: '44px',
                height: '44px',
                minWidth: '44px',
                minHeight: '44px',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#ffffff',
                fontSize: '1rem',
                fontWeight: 700,
                flexShrink: 0
              }}
            >
              {employee?.avatar || employee?.name?.slice(0, 2).toUpperCase()}
            </div>
            <div>
              <span className="modal-emp-label" style={{ fontSize: '0.72rem', textTransform: 'uppercase', color: 'var(--text-muted)', fontWeight: 600 }}>Funcionário</span>
              <h4 className="modal-emp-name" style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--scada-purple-deep)', margin: 0 }}>{employee?.name}</h4>
            </div>
          </div>

          {/* Duração do Almoço */}
          <div className="form-group">
            <label className="form-label">Duração do Almoço:</label>
            <div className="duration-buttons-row">
              {[20, 30, 40, 45, 60].map((mins) => (
                <button
                  type="button"
                  key={mins}
                  className={`btn-duration-choice ${duration === mins ? 'active' : ''}`}
                  style={{ borderRadius: '9999px' }}
                  onClick={() => setDuration(mins)}
                >
                  {mins} min
                </button>
              ))}
            </div>
          </div>

          {/* Horário de Início e Fim */}
          <div className="form-group">
            <div className="time-inputs-grid">
              <div>
                <label className="form-label">Início:</label>
                <div className="time-input-wrap">
                  <input
                    type="time"
                    step={currentInterval * 60}
                    value={startTime}
                    onChange={(e) => setStartTime(e.target.value)}
                    className="time-picker-input"
                    required
                  />
                </div>
                <div className="time-stepper-buttons" style={{ display: 'flex', gap: '6px', marginTop: '8px' }}>
                  <button type="button" className="btn-time-step" style={{ borderRadius: '9999px', padding: '4px 10px', fontSize: '0.75rem', fontWeight: 600, border: '1.5px solid var(--border-color)', background: 'var(--bg-subtle)', color: 'var(--text-main)', cursor: 'pointer' }} onClick={() => handleAdjustStart(-currentInterval * 2)} title={`-${currentInterval * 2} min`}>-{currentInterval * 2}m</button>
                  <button type="button" className="btn-time-step" style={{ borderRadius: '9999px', padding: '4px 10px', fontSize: '0.75rem', fontWeight: 600, border: '1.5px solid var(--border-color)', background: 'var(--bg-subtle)', color: 'var(--text-main)', cursor: 'pointer' }} onClick={() => handleAdjustStart(-currentInterval)} title={`-${currentInterval} min`}>-{currentInterval}m</button>
                  <button type="button" className="btn-time-step" style={{ borderRadius: '9999px', padding: '4px 10px', fontSize: '0.75rem', fontWeight: 600, border: '1.5px solid var(--border-color)', background: 'var(--bg-subtle)', color: 'var(--text-main)', cursor: 'pointer' }} onClick={() => handleAdjustStart(currentInterval)} title={`+${currentInterval} min`}>+{currentInterval}m</button>
                  <button type="button" className="btn-time-step" style={{ borderRadius: '9999px', padding: '4px 10px', fontSize: '0.75rem', fontWeight: 600, border: '1.5px solid var(--border-color)', background: 'var(--bg-subtle)', color: 'var(--text-main)', cursor: 'pointer' }} onClick={() => handleAdjustStart(currentInterval * 2)} title={`+${currentInterval * 2} min`}>+{currentInterval * 2}m</button>
                </div>
              </div>

              <div>
                <label className="form-label">Fim:</label>
                <div className="time-input-wrap">
                  <input
                    type="time"
                    value={endTime}
                    readOnly
                    className="time-picker-input bg-slate-100 cursor-not-allowed"
                  />
                </div>
                <span className="time-hint text-xs text-slate-400">
                  Calculado automaticamente ({duration} min)
                </span>
              </div>
            </div>
          </div>

          {/* Alerta de Conflito em Tempo Real */}
          {conflictWarning ? (
            <div className="conflict-alert-box animate-shake" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '10px', background: 'var(--conflict-bg)', border: '1px solid var(--conflict-border)', padding: '12px 16px', borderRadius: 'var(--radius-md)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <AlertTriangle size={18} className="text-rose-500 shrink-0" />
                <div className="conflict-alert-text" style={{ fontSize: '0.82rem', color: 'var(--conflict-text)' }}>
                  <strong>Atenção:</strong> {conflictWarning}
                </div>
              </div>
              <button
                type="button"
                className="btn-secondary"
                style={{ borderRadius: '9999px', fontSize: '0.78rem', padding: '5px 12px', flexShrink: 0 }}
                onClick={handleSuggestSlot}
                title="Encontrar próximo horário vago"
              >
                <Wand2 size={13} />
                <span>Sugerir livre</span>
              </button>
            </div>
          ) : sharedShiftNames.length > 0 ? (
            <div className="shared-shift-box" style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'var(--scada-purple-subtle)', border: '1px solid var(--border-color)', padding: '10px 14px', borderRadius: 'var(--radius-md)', fontSize: '0.8rem', color: 'var(--text-main)' }}>
              <span style={{ fontSize: '1.1rem' }}>👥</span>
              <span>Almoçando no mesmo turno com: <strong>{sharedShiftNames.join(', ')}</strong>. Atendimento aos clientes garantido pelos colegas de plantão!</span>
            </div>
          ) : (
            <div className="success-slot-box" style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'var(--working-bg)', border: '1px solid var(--working-border)', padding: '10px 14px', borderRadius: 'var(--radius-md)', fontSize: '0.82rem', color: 'var(--working-text)' }}>
              <Check size={16} className="text-emerald-500" />
              <span>Horário disponível e com atendimento aos clientes 100% garantido!</span>
            </div>
          )}

          {/* Rodapé de Ações */}
          <div className="modal-footer">
            {slot && (
              <button
                type="button"
                className="btn-danger-outline"
                style={{ borderRadius: '9999px' }}
                onClick={() => {
                  onDelete(slot.id);
                  onClose();
                }}
              >
                <Trash2 size={14} />
                <span>Remover Horário</span>
              </button>
            )}
            <div className="modal-footer-right" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <button type="button" className="btn-secondary" style={{ borderRadius: '9999px' }} onClick={onClose}>
                Cancelar
              </button>
              <button type="submit" className="btn-primary" style={{ borderRadius: '9999px' }}>
                Salvar Horário
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
